winget uninstall --name "Clipchamp"
winget uninstall --name "Power Automate"
winget uninstall --name "Office"
winget uninstall --name "Hub de commentaires"
winget uninstall --name "Xbox Game Bar Plugin"
winget uninstall --name "Xbox Game Bar"
winget uninstall --name "Xbox Identity Provider"
winget uninstall --name "Xbox Game Speech Window"
winget uninstall --name "Enregistreur vocal Windows"
winget uninstall --name "Courrier et calendrier"
winget uninstall --name "Assistance rapide"
winget uninstall --name "Microsoft.OneDrive"

winget uninstall --id "Microsoft.549981C3F5F10_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.BingNews_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.BingWeather_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.GamingApp_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.GetHelp_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.Getstarted_8wekyb3d8bbwe"
winget uninstall --id "Microsoft Solitaire Collection"
winget uninstall --id "Microsoft.People_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.Todos_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.WindowsMaps_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.WindowsStore_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.Xbox.TCUI_8wekyb3d8bbwe"
winget uninstall --id "Microsoft.YourPhone_8wekyb3d8bbwe"
winget uninstall --id "SpotifyAB.SpotifyMusic_zpdnekdrzrea0"