winget uninstall "Clipchamp"
winget uninstall "Microsoft.549981C3F5F10_8wekyb3d8bbwe"
winget uninstall "Microsoft.BingNews_8wekyb3d8bbwe"
winget uninstall "Microsoft.BingWeather_8wekyb3d8bbwe"
winget uninstall "Microsoft.GamingApp_8wekyb3d8bbwe"
winget uninstall "Microsoft.GetHelp_8wekyb3d8bbwe"
winget uninstall "Microsoft.Getstarted_8wekyb3d8bbwe"
winget uninstall "Microsoft Solitaire Collection"
winget uninstall "Microsoft.People_8wekyb3d8bbwe"
winget uninstall "Power Automate"
winget uninstall "Microsoft.Todos_8wekyb3d8bbwe"
winget uninstall "Hub de commentaires"
winget uninstall "Microsoft.WindowsMaps_8wekyb3d8bbwe"
winget uninstall "Enregistreur vocal Windows"
winget uninstall "Microsoft.WindowsStore_8wekyb3d8bbwe
winget uninstall "Microsoft.Xbox.TCUI_8wekyb3d8bbwe"
winget uninstall "Xbox Game Bar Plugin"
winget uninstall "Xbox Game Bar"
winget uninstall "Xbox Identity Provider"
winget uninstall "Xbox Game Speech Window"
winget uninstall "Microsoft.YourPhone_8wekyb3d8bbwe"
winget uninstall "Assistance rapide"
winget uninstall "Microsoft.OneDrive"
winget uninstall "SpotifyAB.SpotifyMusic_zpdnekdrzrea0"
winget uninstall "Courrier et calendrier"
winget uninstall "Office"
